# Generated by Django 4.0 on 2022-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_group_admin_alter_group_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to='mainpage.UserDetail'),
        ),
    ]
