# Generated by Django 4.0 on 2022-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_group_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editors', to='mainpage.UserDetail'),
        ),
        migrations.AlterField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='mainpage.UserDetail'),
        ),
    ]
