# Generated by Django 4.0 on 2022-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_group_editors_alter_group_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('photos', models.ManyToManyField(blank=True, null=True, related_name='photos', to='mainpage.Photo')),
            ],
        ),
    ]
